changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - github-actions
      - dependabot
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
    - title: New Features
      labels:
        - enhancement
        - feature
    - title: Bug Fixes
      labels:
        - bug
        - fix
    - title: Infrastructure & CI
      labels:
        - infrastructure
        - ci
        - deployment
    - title: Documentation
      labels:
        - documentation
    - title: Other Changes
      labels:
        - "*"
