# Development overrides for docker-compose.yml
# This file is automatically loaded by docker-compose

version: '3.8'

services:
  app:
    volumes:
      - ./app:/app/app
      - ./scripts:/app/scripts
    environment:
      - DEBUG=True
      - RELOAD=True

  celery-worker:
    volumes:
      - ./app:/app/app
      - ./scripts:/app/scripts
    environment:
      - DEBUG=True

  celery-beat:
    volumes:
      - ./app:/app/app
      - ./scripts:/app/scripts
    environment:
      - DEBUG=True

  celery-flower:
    volumes:
      - ./app:/app/app
      - ./scripts:/app/scripts
    environment:
      - DEBUG=True

