version: '3.8'

services:
  app:
    build: .
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/codecollection_registry
      - GITHUB_TOKEN=your_github_token_here
      - GITHUB_WEBHOOK_SECRET=your_webhook_secret_here
      - SECRET_KEY=dev-secret-key-change-in-production
      - REDIS_URL=redis://redis:6379/0
      - ENVIRONMENT=development
      - DEBUG=True
    depends_on:
      - db
      - redis
    volumes:
      - ./app:/app/app
      - ./scripts:/app/scripts
    command: sh -c "python scripts/create_raw_data_tables.py && uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload"

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=codecollection_registry
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery-worker:
    build: .
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/codecollection_registry
      - REDIS_URL=redis://redis:6379/0
      - ENVIRONMENT=development
      - DEBUG=True
    depends_on:
      - db
      - redis
    command: celery -A app.tasks.celery_app worker --loglevel=info --concurrency=2
    restart: unless-stopped

  celery-beat:
    build: .
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/codecollection_registry
      - REDIS_URL=redis://redis:6379/0
      - ENVIRONMENT=development
      - DEBUG=True
    depends_on:
      - db
      - redis
    command: celery -A app.tasks.celery_app beat --loglevel=info
    restart: unless-stopped

  celery-flower:
    image: mher/flower:2.0
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
