# MCP Documentation & Knowledge Sources Configuration
# 
# This file defines external documentation, examples, and knowledge sources
# that can be indexed and searched alongside codebundles.
#
# Categories:
#   - documentation: Official docs, guides, reference materials
#   - examples: Sample code, tutorials, walkthroughs  
#   - libraries: Robot Framework keyword libraries
#   - faq: Common questions and troubleshooting guides
#   - community: Blog posts, videos, external resources

sources:

  # =========================================================================
  # Official Documentation
  # =========================================================================
  documentation:
    - name: CodeBundle Development Guide
      url: https://docs.runwhen.com/authors/
      description: Complete guide to developing RunWhen CodeBundles including structure, syntax, and best practices
      topics:
        - development
        - best-practices
        - getting-started
        - structure
      priority: high
      
    - name: Environment Variables and Configuration
      url: https://docs.runwhen.com/authors/codebundle-basics#CodeBundleBasics-EnvironmentVariables
      description: Managing environment variables and configuration in CodeBundles
      topics:
        - configuration
        - environment-variables
        - setup
        - variables
      priority: medium
      
    - name: Task and SLI Development
      url: https://docs.runwhen.com/authors/codebundle-basics
      description: Creating tasks for automation and SLIs (Service Level Indicators) for monitoring
      topics:
        - tasks
        - slis
        - metrics
        - monitoring
        - health-checks
      priority: high
      
    - name: Generation Rules and Discovery
      url: https://docs.runwhen.com/authors/generation-rules
      description: How to configure CodeBundles for automatic discovery and generation of workspace items
      topics:
        - discovery
        - automation
        - generation-rules
        - templates
      priority: medium
      
    - name: Testing and Debugging CodeBundles
      url: https://docs.runwhen.com/authors/codebundle-testing
      description: Best practices for testing and debugging CodeBundles during development
      topics:
        - testing
        - debugging
        - troubleshooting
        - development
      priority: medium

  # =========================================================================
  # RunWhen Local
  # =========================================================================
  runwhen_local:
    - name: RunWhen Local Installation Guide
      url: https://docs.runwhen.com/public/v/runwhen-local/user-guide/features/getting-started
      description: |
        How to install RunWhen Local using Helm (Kubernetes), Docker, or Docker Compose. 
        RunWhen Local discovers your cloud and Kubernetes resources, matches them to relevant 
        CodeBundles, and generates troubleshooting commands you can run immediately.
        Install with Helm: helm repo add runwhen-contrib https://runwhen-contrib.github.io/helm-charts && 
        helm install runwhen-local runwhen-contrib/runwhen-local -n runwhen-local --create-namespace.
        Or with Docker: docker run -p 8081:8081 ghcr.io/runwhen-contrib/runwhen-local:latest.
        Access the UI at http://localhost:8081.
      topics:
        - install
        - installation
        - runwhen-local
        - local
        - helm
        - docker
        - getting-started
        - setup
      priority: high

    - name: RunWhen Local Configuration
      url: https://docs.runwhen.com/public/v/runwhen-local/user-guide/features/configuration
      description: Configure RunWhen Local via workspaceInfo.yaml to set up kubeconfigs, cloud credentials, namespace mappings, and discovery settings.
      topics:
        - configuration
        - runwhen-local
        - kubeconfig
        - cloud-credentials
        - workspaceInfo
      priority: high

    - name: RunWhen Local Troubleshooting
      url: https://docs.runwhen.com/public/v/runwhen-local/user-guide/features/troubleshooting
      description: Troubleshoot common RunWhen Local issues including missing resources, slow discovery, and connectivity problems. Check logs and restart discovery.
      topics:
        - troubleshooting
        - runwhen-local
        - debug
        - issues
      priority: medium

  # =========================================================================
  # Cloud Discovery Configuration
  # =========================================================================
  cloud_discovery:
    - name: Azure DevOps Discovery
      url: https://docs.runwhen.com/public/azure-devops-discovery
      description: Configure Azure DevOps discovery to index organizations, projects, repositories, pipelines, and releases. Supports PAT, Service Principal, and DefaultAzureCredential authentication.
      topics:
        - azure-devops
        - ado
        - discovery
        - pipelines
        - repositories
        - authentication
        - service-principal
        - pat
      priority: high
      
    - name: Kubernetes Discovery Configuration
      url: https://docs.runwhen.com/public/kubernetes
      description: Configure Kubernetes cluster discovery including namespaces, deployments, services, and workloads
      topics:
        - kubernetes
        - discovery
        - clusters
        - namespaces
        - workloads
      priority: high
      
    - name: AWS Discovery Configuration
      url: https://docs.runwhen.com/public/amazon-web-services
      description: Configure AWS resource discovery including EC2, EKS, RDS, S3, and other AWS services
      topics:
        - aws
        - discovery
        - ec2
        - eks
        - rds
        - s3
        - cloud
      priority: high
      
    - name: Azure Discovery Configuration
      url: https://docs.runwhen.com/public/microsoft-azure
      description: Configure Azure resource discovery including AKS, App Services, databases, and Azure resources
      topics:
        - azure
        - discovery
        - aks
        - app-service
        - cloud
      priority: high
      
    - name: GCP Discovery Configuration
      url: https://docs.runwhen.com/public/google-cloud-platform
      description: Configure GCP resource discovery including GKE, Cloud Run, Cloud SQL, and GCP services
      topics:
        - gcp
        - discovery
        - gke
        - cloud-run
        - cloud-sql
        - cloud
      priority: high

  # =========================================================================
  # RunWhen Platform
  # =========================================================================
  platform:
    - name: RunWhen Platform Overview
      url: https://docs.runwhen.com/public/runwhen-platform
      description: Overview of the RunWhen Platform including workspaces, SLXs, CodeBundles, and how they work together to automate troubleshooting and monitoring
      topics:
        - platform
        - overview
        - introduction
        - runwhen
      priority: high

    - name: Workspace Configuration
      url: https://docs.runwhen.com/public/runwhen-platform/workspaces
      description: Guide to configuring RunWhen workspaces including adding clusters, setting up discovery, and organizing resources
      topics:
        - workspace
        - configuration
        - setup
        - organization
      priority: high

    - name: Secrets Management
      url: https://docs.runwhen.com/public/runwhen-platform/secrets
      description: How to manage secrets in RunWhen including kubeconfigs, API keys, cloud credentials (AWS, Azure, GCP), and service account tokens
      topics:
        - secrets
        - credentials
        - security
        - kubeconfig
        - api-keys
        - authentication
      priority: high

    - name: SLX Configuration
      url: https://docs.runwhen.com/public/runwhen-platform/slx-configuration
      description: Guide to configuring Service Level Expectations (SLX) including thresholds, alerting, and CodeBundle bindings
      topics:
        - slx
        - service-level
        - configuration
        - thresholds
        - alerting
      priority: medium

  # =========================================================================
  # Library References (keyword_usage_help / find_library_info tools)
  # =========================================================================
  libraries:
    - name: RW.CLI Library
      url: https://docs.runwhen.com/public/runwhen-authors/keyword-libraries/rw-cli
      description: Execute shell commands and CLI tools like kubectl, aws, gcloud, and other CLI tools. The most commonly used library in CodeBundles.
      topics:
        - cli
        - shell
        - kubectl
        - aws
        - gcloud
        - command
        - bash
        - rw.cli
      usage_examples:
        - "RW.CLI.Run Cli    cmd=kubectl get pods -n \\${NAMESPACE}"
        - "RW.CLI.Run Cli    cmd=aws eks describe-cluster --name \\${CLUSTER_NAME}"
      priority: high

    - name: RW.K8s Library
      url: https://docs.runwhen.com/public/runwhen-authors/keyword-libraries/rw-k8s
      description: Kubernetes-specific operations and helpers for working with pods, deployments, services, namespaces, and other K8s resources
      topics:
        - kubernetes
        - k8s
        - pods
        - deployments
        - services
        - namespaces
        - rw.k8s
      priority: high

    - name: RW.Core Library
      url: https://docs.runwhen.com/public/runwhen-authors/keyword-libraries/rw-core
      description: Core utility functions for CodeBundle development including variable handling, output formatting, and common helpers
      topics:
        - core
        - utilities
        - helpers
        - common
        - variables
        - rw.core
      priority: medium

    - name: RW.AWS Library
      url: https://docs.runwhen.com/public/runwhen-authors/keyword-libraries/rw-aws
      description: AWS-specific operations and helpers for EC2, S3, EKS, Lambda, RDS, and other AWS services
      topics:
        - aws
        - amazon
        - ec2
        - s3
        - lambda
        - eks
        - rds
        - rw.aws
      priority: high

    - name: RW.Azure Library
      url: https://docs.runwhen.com/public/runwhen-authors/keyword-libraries/rw-azure
      description: Azure-specific operations and helpers for AKS, App Services, databases, and Azure resources
      topics:
        - azure
        - microsoft
        - aks
        - app-service
        - webapp
        - functionapp
        - rw.azure
      priority: high

    - name: RW.GCP Library
      url: https://docs.runwhen.com/public/runwhen-authors/keyword-libraries/rw-gcp
      description: Google Cloud Platform specific operations for GKE, Cloud Run, Cloud SQL, and GCP services
      topics:
        - gcp
        - google
        - gke
        - cloud-run
        - compute
        - rw.gcp
      priority: high

  # =========================================================================
  # CodeBundle Development (codebundle tools)
  # =========================================================================
  codebundle_development:
    - name: Robot Framework Basics for CodeBundles
      url: https://docs.runwhen.com/public/runwhen-authors/codebundle-development/robot-framework-basics
      description: Introduction to Robot Framework syntax for CodeBundle development including keywords, tasks, variables, and test structure
      topics:
        - robot
        - robot-framework
        - syntax
        - keywords
        - tasks
      priority: high

    - name: SLI Development Guide
      url: https://docs.runwhen.com/public/runwhen-authors/codebundle-development/sli-development
      description: Guide to creating Service Level Indicator (SLI) CodeBundles that measure metrics and return numeric values for monitoring
      topics:
        - sli
        - service-level-indicator
        - metrics
        - monitoring
        - sli.robot
      priority: high

    - name: TaskSet Development Guide
      url: https://docs.runwhen.com/public/runwhen-authors/codebundle-development/taskset-development
      description: Guide to creating TaskSet CodeBundles for automated runbooks with multiple tasks for troubleshooting and remediation
      topics:
        - taskset
        - runbook
        - automation
        - tasks
        - remediation
        - runbook.robot
      priority: high

  # =========================================================================
  # Contributing & GitHub Issues (request_codebundle / check_existing_requests tools)
  # =========================================================================
  contributing:
    - name: Contributing CodeBundles
      url: https://docs.runwhen.com/public/runwhen-authors/contributing
      description: |
        How to contribute CodeBundles to the RunWhen community:
        1. Fork the appropriate codecollection repository on GitHub
        2. Create your CodeBundle following the development guide
        3. Test it locally using robot or RunWhen Local
        4. Submit a pull request for community review
        Contributions help the entire community troubleshoot and monitor their infrastructure.
      topics:
        - contribute
        - contribution
        - pull-request
        - community
        - open-source
        - github
      priority: high

    - name: Requesting New CodeBundles
      url: https://github.com/runwhen-contrib/rw-cli-codecollection/issues
      description: |
        You can request new CodeBundles by creating a GitHub issue on the appropriate codecollection repository.
        Include: the platform/service you need help with, what the CodeBundle should do,
        any specific CLI commands or APIs involved, and your use case.
        The community and RunWhen team review requests and may implement them.
      topics:
        - request
        - codebundle-request
        - github-issue
        - feature-request
        - new-codebundle
      priority: medium

  # =========================================================================
  # Examples & Tutorials (codebundle tools)
  # =========================================================================
  examples:
    - name: Kubernetes Deployment Health Check
      url: https://github.com/runwhen-contrib/rw-public-codecollection/tree/main/codebundles/k8s-deployment-healthcheck
      description: A simple example of a Kubernetes deployment health check CodeBundle that checks pod status, readiness, and resource usage
      topics:
        - example
        - health-check
        - kubernetes
        - deployment
        - getting-started
      priority: high

    - name: Kubernetes Namespace Troubleshooting
      url: https://github.com/runwhen-contrib/rw-cli-codecollection/tree/main/codebundles/k8s-namespace-healthcheck
      description: Comprehensive namespace troubleshooting CodeBundle that checks events, pod health, resource quotas, and network policies
      topics:
        - example
        - troubleshooting
        - kubernetes
        - namespace
      priority: high

    - name: AWS EKS Cluster Health Check
      url: https://github.com/runwhen-contrib/rw-cli-codecollection/tree/main/codebundles/aws-eks-cluster-healthcheck
      description: AWS EKS cluster health check CodeBundle that validates cluster status, node health, and add-on configurations
      topics:
        - example
        - aws
        - eks
        - health-check
      priority: medium

  # =========================================================================
  # FAQ & Troubleshooting
  # =========================================================================
  faq:
    - question: How do I use kubectl in a CodeBundle?
      answer: |
        Use the RW.CLI.Run Cli keyword with your kubectl command:
        
        ```robot
        RW.CLI.Run Cli    cmd=kubectl get pods -n ${NAMESPACE}
            ...    kubeconfig=${KUBECONFIG}
        ```
        
        Make sure you have:
        1. A kubeconfig secret configured in your workspace
        2. The NAMESPACE variable defined in your meta.yaml
      topics:
        - kubectl
        - kubernetes
        - cli

    - question: How do I access cloud provider credentials?
      answer: |
        Cloud credentials are configured as secrets in your workspace and accessed via environment variables:
        
        For AWS: Use the aws-credentials secret type
        For GCP: Use the gcp-service-account secret type  
        For Azure: Use the azure-credentials secret type
        
        These are automatically injected into your CodeBundle's environment.
      topics:
        - credentials
        - aws
        - gcp
        - azure
        - secrets

    - question: How do I create an SLI vs a Task?
      answer: |
        SLIs (Service Level Indicators) return a numeric metric value (0-1 or percentage).
        Tasks perform actions and may return success/failure.
        
        In your robot file:
        - SLI: Use the `sli.robot` filename and return a numeric value
        - Task: Use `runbook.robot` or `taskset.robot` and perform automation
      topics:
        - sli
        - task
        - monitoring
        - automation

    - question: How do I debug a CodeBundle?
      answer: |
        Tips for debugging CodeBundles:
        1. Use Log statements to output variable values
        2. Test locally with: robot --variable NAMESPACE:default sli.robot
        3. Check the RunSession logs in the RunWhen platform
        4. Use RunWhen Local to test CodeBundles against real infrastructure
        5. Add RW.Core.Add Pre To Report for detailed output
      topics:
        - debug
        - debugging
        - troubleshooting
        - logs
        - testing

    - question: What is the difference between SLI and TaskSet?
      answer: |
        SLI (Service Level Indicator) CodeBundles measure a metric and return a numeric value (0-1 or percentage).
        They are used for continuous monitoring and alerting.
        
        TaskSet CodeBundles run automated runbooks with multiple tasks that can be triggered on-demand or 
        automatically. They are used for remediation and troubleshooting.
        
        Use SLIs for monitoring, TaskSets for remediation.
      topics:
        - sli
        - taskset
        - difference
        - types
        - monitoring
        - automation

    - question: How do I contribute a CodeBundle?
      answer: |
        To contribute a CodeBundle:
        1. Fork the appropriate codecollection repository (e.g., rw-cli-codecollection)
        2. Create your CodeBundle following the development guide
        3. Test it locally using robot or RunWhen Local
        4. Submit a pull request on GitHub
        5. The community will review and merge
      topics:
        - contribute
        - contribution
        - pull-request
        - community
        - github

# =========================================================================
# Index Configuration
# =========================================================================
index_config:
  # How often to re-index documentation sources (in hours)
  refresh_interval: 24
  
  # Whether to crawl linked pages from documentation URLs
  # When enabled, the indexer will fetch actual page content for better semantic search
  crawl_linked_pages: true
  
  # Maximum depth for crawling
  max_crawl_depth: 3
  
  # Include code examples in embeddings
  include_code_examples: true
  
  # Weights for search relevance
  relevance_weights:
    title_match: 2.0
    topic_match: 1.5
    description_match: 1.0
    content_match: 0.8


