# MCP Documentation & Knowledge Sources Configuration
# 
# This file defines external documentation, examples, and knowledge sources
# that can be indexed and searched alongside codebundles.
#
# Categories:
#   - documentation: Official docs, guides, reference materials
#   - examples: Sample code, tutorials, walkthroughs  
#   - libraries: Robot Framework keyword libraries
#   - faq: Common questions and troubleshooting guides
#   - community: Blog posts, videos, external resources

sources:

  # =========================================================================
  # Official Documentation
  # =========================================================================
  documentation:
    - name: CodeBundle Development Guide
      url: https://docs.runwhen.com/authors/
      description: Complete guide to developing RunWhen CodeBundles including structure, syntax, and best practices
      topics:
        - development
        - best-practices
        - getting-started
        - structure
      priority: high
      
    - name: Environment Variables and Configuration
      url: https://docs.runwhen.com/authors/codebundle-basics#CodeBundleBasics-EnvironmentVariables
      description: Managing environment variables and configuration in CodeBundles
      topics:
        - configuration
        - environment-variables
        - setup
        - variables
      priority: medium
      
    - name: Task and SLI Development
      url: https://docs.runwhen.com/authors/codebundle-basics
      description: Creating tasks for automation and SLIs (Service Level Indicators) for monitoring
      topics:
        - tasks
        - slis
        - metrics
        - monitoring
        - health-checks
      priority: high
      
    - name: Generation Rules and Discovery
      url: https://docs.runwhen.com/authors/generation-rules
      description: How to configure CodeBundles for automatic discovery and generation of workspace items
      topics:
        - discovery
        - automation
        - generation-rules
        - templates
      priority: medium
      
    - name: Testing and Debugging CodeBundles
      url: https://docs.runwhen.com/authors/codebundle-testing
      description: Best practices for testing and debugging CodeBundles during development
      topics:
        - testing
        - debugging
        - troubleshooting
        - development
      priority: medium

  # =========================================================================
  # Cloud Discovery Configuration
  # =========================================================================
  cloud_discovery:
    - name: Azure DevOps Discovery
      url: https://docs.runwhen.com/public/azure-devops-discovery
      description: Configure Azure DevOps discovery to index organizations, projects, repositories, pipelines, and releases. Supports PAT, Service Principal, and DefaultAzureCredential authentication.
      topics:
        - azure-devops
        - ado
        - discovery
        - pipelines
        - repositories
        - authentication
        - service-principal
        - pat
      priority: high
      
    - name: Kubernetes Discovery Configuration
      url: https://docs.runwhen.com/public/kubernetes
      description: Configure Kubernetes cluster discovery including namespaces, deployments, services, and workloads
      topics:
        - kubernetes
        - discovery
        - clusters
        - namespaces
        - workloads
      priority: high
      
    - name: AWS Discovery Configuration
      url: https://docs.runwhen.com/public/amazon-web-services
      description: Configure AWS resource discovery including EC2, EKS, RDS, S3, and other AWS services
      topics:
        - aws
        - discovery
        - ec2
        - eks
        - rds
        - s3
        - cloud
      priority: high
      
    - name: Azure Discovery Configuration
      url: https://docs.runwhen.com/public/microsoft-azure
      description: Configure Azure resource discovery including AKS, App Services, databases, and Azure resources
      topics:
        - azure
        - discovery
        - aks
        - app-service
        - cloud
      priority: high
      
    - name: GCP Discovery Configuration
      url: https://docs.runwhen.com/public/google-cloud-platform
      description: Configure GCP resource discovery including GKE, Cloud Run, Cloud SQL, and GCP services
      topics:
        - gcp
        - discovery
        - gke
        - cloud-run
        - cloud-sql
        - cloud
      priority: high

  # =========================================================================
  # Library References
  # =========================================================================
  libraries:
    - name: RW.CLI.RunCli
      url: https://docs.runwhen.com/public/runwhen-authors/rw-cli-runcli
      description: Execute shell commands and CLI tools. Supports kubectl, aws, gcloud, and other CLI tools.
      category: cli
      topics:
        - cli
        - shell
        - kubectl
        - aws
        - gcloud
      usage_examples:
        - "RW.CLI.Run Cli    cmd=kubectl get pods -n \\${NAMESPACE}"
        - "RW.CLI.Run Cli    cmd=aws eks describe-cluster --name \\${CLUSTER_NAME}"
      common_use_cases:
        - Running kubectl commands
        - Executing AWS CLI commands
        - Running gcloud commands
        - General shell script execution
      priority: high

  # =========================================================================
  # Examples & Tutorials  
  # =========================================================================
  examples:
    - name: Simple Health Check Example
      url: https://github.com/runwhen-contrib/rw-public-codecollection/tree/main/codebundles/k8s-deployment-healthcheck
      description: A simple example of a Kubernetes deployment health check CodeBundle
      topics:
        - example
        - health-check
        - kubernetes
        - getting-started
      priority: high
      
    - name: Troubleshooting Task Example
      url: https://github.com/runwhen-contrib/rw-cli-codecollection/tree/main/codebundles/k8s-namespace-healthcheck
      description: Example of a comprehensive namespace troubleshooting CodeBundle with multiple tasks
      topics:
        - example
        - troubleshooting
        - kubernetes
        - namespace
      priority: high
      
    - name: AWS CodeBundle Example
      url: https://github.com/runwhen-contrib/rw-cli-codecollection/tree/main/codebundles/aws-eks-cluster-healthcheck
      description: Example of an AWS EKS cluster health check CodeBundle
      topics:
        - example
        - aws
        - eks
        - health-check
      priority: medium

  # =========================================================================
  # FAQ & Troubleshooting
  # =========================================================================
  faq:
    - question: How do I use kubectl in a CodeBundle?
      answer: |
        Use the RW.CLI.Run Cli keyword with your kubectl command:
        
        ```robot
        RW.CLI.Run Cli    cmd=kubectl get pods -n ${NAMESPACE}
            ...    kubeconfig=${KUBECONFIG}
        ```
        
        Make sure you have:
        1. A kubeconfig secret configured in your workspace
        2. The NAMESPACE variable defined in your meta.yaml
      topics:
        - kubectl
        - kubernetes
        - cli
        
    - question: How do I access cloud provider credentials?
      answer: |
        Cloud credentials are configured as secrets in your workspace and accessed via environment variables:
        
        For AWS: Use the aws-credentials secret type
        For GCP: Use the gcp-service-account secret type  
        For Azure: Use the azure-credentials secret type
        
        These are automatically injected into your CodeBundle's environment.
      topics:
        - credentials
        - aws
        - gcp
        - azure
        - secrets
        
    - question: How do I create an SLI vs a Task?
      answer: |
        SLIs (Service Level Indicators) return a numeric metric value (0-1 or percentage).
        Tasks perform actions and may return success/failure.
        
        In your robot file:
        - SLI: Use the `sli.robot` filename and return a numeric value
        - Task: Use `runbook.robot` or `taskset.robot` and perform automation
      topics:
        - sli
        - task
        - monitoring
        - automation

# =========================================================================
# Index Configuration
# =========================================================================
index_config:
  # How often to re-index documentation sources (in hours)
  refresh_interval: 24
  
  # Whether to crawl linked pages from documentation URLs
  # When enabled, the indexer will fetch actual page content for better semantic search
  crawl_linked_pages: true
  
  # Maximum depth for crawling
  max_crawl_depth: 1
  
  # Include code examples in embeddings
  include_code_examples: true
  
  # Weights for search relevance
  relevance_weights:
    title_match: 2.0
    topic_match: 1.5
    description_match: 1.0
    content_match: 0.8


