version: '3'

vars:
  PROJECT_NAME: runwhen-mcp-server
  IMAGE_NAME: runwhen-mcp-server

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  # ===========================================
  # Core Commands
  # ===========================================
  build:
    desc: Build the Docker image
    cmds:
      - |
        if [ -f az.secret ]; then
          source az.secret
        fi
        docker-compose build

  start:
    desc: Start the HTTP API server and web client
    cmds:
      - |
        if [ -f az.secret ]; then
          source az.secret
        fi
        docker-compose up -d mcp-http web-client
      - |
        echo "✅ Services running:"
        echo "   API Server: http://localhost:8000"
        echo "   API Docs:   http://localhost:8000/docs"
        echo "   Web Client: http://localhost:8080"

  stop:
    desc: Stop the server
    cmds:
      - docker-compose down

  logs:
    desc: View server logs
    cmds:
      - docker-compose logs -f mcp-http web-client

  test:
    desc: Run tests
    cmds:
      - docker-compose run --rm test

  # ===========================================
  # Indexing Commands (legacy — indexing now handled by backend)
  # ===========================================
  index:
    desc: "[Legacy] Run indexer with Azure OpenAI embeddings"
    cmds:
      - echo "⚠️  Indexing is now handled by the backend Registry API."
      - echo "   The MCP server is stateless and fetches data from REGISTRY_API_URL."
      - echo "   To re-index, trigger a sync via the backend admin API."

  index-local:
    desc: "[Legacy] Run indexer with local embeddings (no API)"
    cmds:
      - echo "⚠️  Indexing is now handled by the backend Registry API."
      - echo "   The MCP server is stateless and fetches data from REGISTRY_API_URL."

  index-status:
    desc: Check MCP server health and backend connectivity
    cmds:
      - |
        echo "🔍 Checking MCP server health..."
        curl -s http://localhost:8000/health | python -m json.tool 2>/dev/null || echo "❌ MCP server not reachable at localhost:8000"

  # ===========================================
  # Cleanup
  # ===========================================
  clean:
    desc: Stop and clean up
    cmds:
      - docker-compose down -v
      - docker system prune -f

  clean-index:
    desc: Remove indexed data (cloned repos + legacy vectordb)
    cmds:
      - rm -rf data/vectordb data/repos data/vector_index.json
      - echo "✅ Index data cleared"
